export const ROLE_USER = 'USER'
export const ROLE_MODERATOR = 'MODERATOR'

export const DIPLOMA_CERTIFICATE='diploma_certificate'
export const UNT_CT_CERTIFICATE='unt_ct_certificate'
export const PHOTO_3x4='photo3x4'
export const HEALTH_086='health_certificate_086'
export const HEALTH_063='health_certificate_063'
export const FLUOROGRAPHY='fluorography'
export const IDENTITY_CARD_FRONT='identity_card_front'
export const IDENTITY_CARD_BACK='identity_card_back'