server:
  port: 8081
  spring:
    profiles:
      active: dev
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/regsystem
    username: regsystem
    password: zhaba12#
    driver-class-name: org.postgresql.Driver
  mail:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    host: smtp.gmail.com
    port: 587
    username: dandibobo537@gmail.com
    frontend:
      url: http://localhost:8080
#  redis:
#    host: localhost:6379
frontend:
  url: http://localhost:8080
emailPassword: 123
jwtKey: 123

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/regsystem
    username: regsystem
    password: zhaba12#
    driver-class-name: org.postgresql.Driver
  profiles: dev
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
---
spring:
  profiles: pre

spring:
  profiles: prod
