spring:
  mail:
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    host: smtp.gmail.com
    port: 587
    username: dandibobo537@gmail.com

server:
  port: 8081
  contextPath: "/api/"